services:
  #nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  #php
  app:
    build:
      dockerfile: ./php/Dockerfile

  #mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: db_user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: example_db

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8099:80"


  #redis
volumes:
  mysqldata:
